### ISSUE TITLE
TODOs for first version

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#18]
@CrusherBob I have done some extensive changes to the mod (see [commits](https://github.com/CptMoore/MechEngineMod/commits/master)).

we now have std engines, xl engines, endo steel and ferros fibrous.

what do you think is still necessary in order to release a first version?

TODO list from my point of view:
- adding engines to all player stock mechs (we need to be able to modify only the center torso of mechs, have to write a patch for modtek to make it possible, will do that though)
- add more xl engines or reduce them to only what the 4 stock SLDF mechs would be using. also add endo steel and ferros fibrous to those SLDF mechs if possible
- figure out a solution where and how to put all our new components on display (stock mechs, shops, salvage, etc.. )

other TODOs?

**Comment by CptMoore** [comment]
> allow mixed heat sinks
> allow partial endo-steel

created issue #22, will solve that

> None of them actually use XL engines

how to solve #8 then? just some shops? a special mission with a nice reward at the end?

>  Especially since the default one crams something like 4 DHS into each leg

lets add all free slots heatsinks to the engines? should give us some nice crit space with minimal tonnage loss, see #23

**Comment by TotalMeltdown** [comment]
Typically, you can add up to 2 extra heatsinks into the engine with the updated 3025 rules but I'm not sure its possible to enable this functionality in the HBS game. 

 "DissipationCapacity": 30 // Seems to be wholly dependent on file name to function. Tested and found that file name of "Gear_HeatSink_Generic_Standard-FusionEngine" will enable use of "DissipationCapacity", while "Gear_FusionEngine_Generic" will not enable.

**Comment by CptMoore** [comment]
> Typically, you can add up to 2 extra heatsinks into the engine with the updated 3025 rules but I'm not sure its possible to enable this functionality in the HBS game.

right now you can add up to (rating - 250) / 25 additional heat sinks intothe engine. Thats one of the core features of this mod.

> "DissipationCapacity": 30 // Seems to be wholly dependent on file name to function. Tested and found that file name of "Gear_HeatSink_Generic_Standard-FusionEngine" will enable use of "DissipationCapacity", while "Gear_FusionEngine_Generic" will not enable.

Dissipation capacity is calculated dynamically already, see the tooltip of an engine https://imgur.com/a/eByjZ9s . Thats necessary since heatsinks are part of the internal components of an engine.

**Comment by CptMoore** [comment]
I believe this is done, we have everything for a first version if we don't care about game balance too much.
