### ISSUE TITLE
add LICENSE to repo

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#19]
I would like this source code to have a specific license, I changed all my repos to be UNLICENSE (a.k.a. public domain) but since this also contains crusher bobs work, I would like his permission first.

**Comment by CrusherBob** [comment]
Hmm, well part of why my original modifications to the code were so clearly labeled was for potential IP issues, depending on what you wanted to do with your original code.  I don't really have a problem with just public domaining the whole thing.

**Comment by CptMoore** [comment]
cool, will do that then
