### ISSUE TITLE
engine heatsink changes and improvements

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#20]
# Current Idea

expand saving and loading of MechComponentRefs/BaseComponentRefs (only for engines though)
- for json reuse SimGameUID (skirmish mechlab)
- for .sav files, SimGameUID is already saved and loaded properly.

SimGameUID would be null/"" or "/dhs+5dhs" indicating if shs engine or dhs engine with how many additional heat sinks that were added after the free heatsinks one gets. shs with 3 additionals would be "+3shs". since we allow mixed if configured, "dhs+2dhs+1shs" should be possible.

have an extra item called "DHS Engine Kit" that converts an engine to double heat sinks, it should be worth 10 DHS items.

when dragging and dropping the kit or heat sinks to center torso, try to integrate those into the engine first. Items in engines can only be removed by dismounting the engine. Add the "DHS Engine Kit" back to inventory including all user added dhs.

engines always come with all free shs installed by default.

**Comment by CptMoore** [comment]
@CrusherBob any objections to the proposed mechanism regarding DHS and SHS for engines?

**Comment by CrusherBob** [comment]
Only thing to add is to make sure that taking the whole engine out of the mech is also handled gracefully.

**Comment by CptMoore** [comment]
just want to say I'm working hard to get this feature working, I have a prototype working but its ugly. I will polish it over the weekend

**Comment by CptMoore** [comment]
ok I finished this idea
