### ISSUE TITLE
how to extract heatsinks from engines

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#24]
in order to remove added heatsinks from an engine, one has to dismount the whole engine.
however in order to dismount an engine, one has to mount another engine in first.
thats kinda excessive for removing heatsinks.

**Comment by CrusherBob** [comment]
Only thing I see on the UI that no one might care if you hijack it to do something else are the 'stock combat loadout' info button (circled letter i, bottom middle)  (Also seems to have same effect as the button by the hardpoints in the upper left), and the (cyan ?) mechlab tutorial button in the upper left.

If you can hijack the buttons, you can just make one of them spit the engine heat sinks back out.

**Comment by CptMoore** [comment]
good idea, will check those out

**Comment by CptMoore** [comment]
yep, once I know how to rename one of those and then make a popup appear with a confirm button, I'll hijack those.

**Comment by CptMoore** [comment]
I wasnt able to hijack those controls, however I will allow the extraction logic to run when dismounting an engine. Installing and uninstalling heatsinks into and from an engine will be cbills and techcost free.

**Comment by CptMoore** [comment]
this is done
