### ISSUE TITLE
Ferro Fibrous armor produces excessive savings

### ISSUE THREAD

**Issue by Doedie** [CptMoore/MechEngineMod#28]
As the title says, Ferrofibrous armor produces savings equal to 1/1.12 (~90%) of armor tonnage, allowing some quite strange builds . I was able to replicate this on both a Locust (4 tons saved) and a Cataphract (~11 tons saved). I was able to correct it by changing:

        public float FerrosFibrousArmorWeightSavingsFactor = 1f / 1.12f;

to

        public float FerrosFibrousArmorWeightSavingsFactor = 0.12f;

Apologies if I'm budging in uninvited, but I have been watching this mod for a while and I love toying around with it!

**Comment by CptMoore** [comment]
ups, yea I reversed the roles for the settings so often, I must have kept it wrong in the end

given max armor:
max armor = max ff armor * 1.12
 => max ff armor = max armor / 1.12
weight savings = max armor - max ff armor
 => weight savings = max armor - max armor / 1.12
 => weight savings = max armor x ( 1 - 1/1.12 )

so the factor is 1 - 1/1.12 =~ 0.1071

> Apologies if I'm budging in uninvited,

you are most welcome to participate: find bugs, introduce ideas and if you can even create PRs. thanks for this issue!
