### ISSUE TITLE
Game stuck on infinite load after updating to the new Modtek and MechEngineMod versions

### ISSUE THREAD

**Issue by Doedie** [CptMoore/MechEngineMod#32]
[output_log mechengine.txt](https://github.com/CptMoore/MechEngineMod/files/2087065/output_log.mechengine.txt)

Running the current versions of BTML, ModTek, DynModLib. I first noticed this after updating everything today, but I reinstalled the Battletech modding tools on a clean mod folder with only the default mods and the MechEngineMod. After pressing new game, it is stuck on an infinite loading screen before the character creation kicks in. Removing the MechEngineMod folder fixes the issue both on my usual mod folder and on the clean install.

**Comment by CptMoore** [comment]
thx, just changed something, hopefully that fixed it, can you recheck?

**Comment by Doedie** [comment]
Made it to the character creation screen normally, yes! It seems to be resolved, I'll let you know if it gets stuck at a later point.

**Comment by CptMoore** [comment]
thanks for testing, that was my bad that it didnt work. added gyros as extra item and only tested the skirmish mechlab
