### ISSUE TITLE
allow an advanced package for enthusiasts

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#42]
since the game does not support large amounts of components (see #38), we should only provide a small number of components with the mod.

some advanced users want to play around with more engines so we still should package in more options.

@Aliencreature did add the more advanced variants.

**Comment by CptMoore** [comment]
@Aliencreature I have updated your advanced branch, can you make a PR and check if everything is in order?

I called your version "more", i might rename it to "moore".

**Comment by CptMoore** [comment]
Ive just merged everything into the main branch again, the "more" stuff is disabled by defaults

**Comment by Aliencreature** [comment]
Will do, sorry for the radio silence, I am out of town today (and yesterday) so I can't do much testing until I am back behind my desktop.

**Comment by CptMoore** [comment]
@Aliencreature I restructured everything again, I call now clan stuff etc... exotics. also put the small cockpit there. exotics is for stuff that isn't finished yet or isn't immersive (e.g. still waiting for a clan mod ;) ).

**Comment by Aliencreature** [comment]
Alright, finally got home and managed to test it. Everything seems to be working fine in skirmish, including the heat effects for stealth armor and XXL engines. Even with the exotic package and RogueTech the mechlab feels much snappier than before. I will start a new sandbox game and see if I hit any road-blocks.

**Comment by CptMoore** [comment]
awesome, I'll close this since we achieved a nice separation of where goes what
