### ISSUE TITLE
Heat efficiency stats miscalculating

### ISSUE THREAD

**Issue by Aliencreature** [CptMoore/MechEngineMod#48]
The heat efficiency popup overestimates the heat sinking ability of a mech by always adding the stock 30 heat/turn.

**Comment by CptMoore** [comment]
it doesn't add anything for me.

maybe some of the other mods you are using messes with the following
CombatGameConstants.json
"InternalHeatSinkCount": 0

I also know that roguetech has its own double heat sink logic built in, maybe that messes stuff up too

**Comment by Aliencreature** [comment]
Damn, sorry for that, I forgot to change up my load order after reinstalling everything. You are right.
