### ISSUE TITLE
add more engine types

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#5]
we currently have
- std
- xl

we could add
- compact 
- light

Note this issues is in conflict with #3

**Comment by CptMoore** [comment]
we might also need more XL engine ratings

**Comment by CptMoore** [comment]
those additional engines are from the future (and not lostech) so unless we make the mod future proof (pun indented) lets not add those engine types

**Comment by CrusherBob** [comment]
Sorry for the lack of action on my part.  Have had to deal with: clogged well filter, broken kitchen sink, and a literal snake getting into the house, plus a cat that now seems to be nervous about the possibility of more snakes getting into the house.  Have mostly been too tired to do anything.  Will try to get my head back in the game on Tuesday.

**Comment by CptMoore** [comment]
@CrusherBob sure no problem, sounds like you have an interesting life going on! I'm right now bothering other people about additional TT rules. At the same time im polishing the base code, I still think it needs more time, right now its perfect to tinker around in skirmish, but the immersive-ness of the campaign still is lacking hugely.
