### ISSUE TITLE
Mechs with stock DHS receive SHS internal sinks

### ISSUE THREAD

**Issue by Aliencreature** [CptMoore/MechEngineMod#50]
This is most prominent in custom variants such as those introduced by RogueTech, but I have a hunch that it affects the SLDF variants already in the story (like the SLDF Black Knight). Upon receiving these mechs, they have double heat sinks with an SHS engine, leading them to be unusable.

Proposed fix: modify the engine fix code to check if there are any DHS on the stock design, and then decide if it should convert the internal sinks to double.

**Comment by CptMoore** [comment]
yea that was inevitable. I now need to implement proper SimGameUID loading to make this happen.

**Comment by CptMoore** [comment]
I implemented proper SimGameUID loading (hopefully) and now it autodetects double heat sinks on mechs and uses dhs engines automatically.
