### ISSUE TITLE
add lore friendly descriptions to all components

### ISSUE THREAD

**Issue by CptMoore** [CptMoore/MechEngineMod#9]
- engines
- engine parts
- endo steel

all need nice UIName Name Details Manufacturer Model

**Comment by CptMoore** [comment]
@CrusherBob any ideas on how to solve this?

**Comment by CrusherBob** [comment]
Know the original engine table had manufacturers by engine rating.  Remember 'Nissan' and 'GM',  But don't don't remember them in the later year rules compilations.  Would assume there are supposed to be several engine manufacturers, and there is probably overlap in the engines they made.

Sarna has a list of the engine manufacturers here: http://www.sarna.net/wiki/Fusion_Engine

**Comment by CptMoore** [comment]
so just add the names that match the ratings we can find on that page, and for the rest its random names from the page?

**Comment by CptMoore** [comment]
I added detail descriptions for most of the component that I think fits and also explains some of the mechanics.

I didn't add any manufacturers
